name: .NET

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk, feature/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/heitech.consoleXt.core/heitech.consoleXt.core.csproj
    - name: Build
      run: dotnet build --no-restore ./src/heitech.consoleXt.core/heitech.consoleXt.core.csproj
    - name: Test
      run: dotnet test --verbosity normal ./tests/heitech.consoleXt.tests/heitech.consoleXt.tests.csproj
